language: c

branches:
    only:
        - master

install:
  - source devtools/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # this builds the binary, unpacks it, and runs the tests
    - conda build devtools/conda-recipe

env:
  matrix:
    - CONDA_PY=27
    - CONDA_PY=33
    - CONDA_PY=34

