package:
  name: wetmsm-dev
  version: !!str 1.0.0


build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - cython
    - mdtraj
    - msmbuilder
  run:
    - python
    - future
    - mdtraj
    - msmbuilder


test:
    imports:
        - wetmsm

about:
  home: https://github.com/mpharrigan/wetmsm
  license: LGPLv2.1+
  summary: 'WetMSM: Solvent dynamics in MSMs'
